Inject additional dependencies into the serializers
google/santa pull request #1078
Opened 2023-04-23 19:33 UTC by mlw

The serializers were using static variables in a couple of places that was fine for production, but made some types of tests difficult since the static variables would outlive the mocks.

This change should have no functional impact on Santa - nothing should change at runtime as part of this restructuring to inject the dependencies.

2023-04-28 08:49 UTC, mlw commented
Please hold up on review - going to store the client mode in the SNTCachedDecision so that lazy client mode lookup isn't needed (also fixes a long standing race that could occur where the mode applied at policy time might not match the mode at logging time, tho this would be quite rare).

2023-04-28 09:36 UTC, mlw commented
PR updated to store the client mode at decision time and remove the client mode lookup function injection.

Good to resume reviewing!

2023-04-28 13:11 UTC, russellhancox requested changes
LGTM

2023-04-28 13:11 UTC, russellhancox commented on Source/common/SNTCachedDecision.h
> +@property SNTClientMode decisionClientMode;
Group this with the decision further up

2023-05-01 18:42 UTC, russellhancox approved these changes

2023-05-01 19:13 UTC, merged