Add support to file monitoring config to invert process exceptions
google/santa pull request #1083
Opened 2023-04-28 08:50 UTC by mlw

Adds support for a new option key in the file monitoring config: `InvertProcessExceptions`. This will allow adding a rule to monitor file access from only specified processes.

2023-04-28 12:04 UTC, pmarkowsky reviewed
Overall looks good. We should update the documentation as part of this.

2023-04-28 12:52 UTC, russellhancox requested changes
LGTM

2023-05-01 18:01 UTC, mlw commented on Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
> +  // TODO(xyz): Need new config item for custom message in UI
https://github.com/google/santa/issues/1084

2023-05-01 18:41 UTC, russellhancox approved these changes

2023-05-01 19:04 UTC, merged