ProcessTree: integrate process tree throughout the event processing lifecycle (3/4)
google/santa pull request #1281
Opened 2024-02-05 23:49 UTC by kallsyms

This PR:
* Instantiates a process tree in SantaDeps, and threads it through to the enricher and proto serializer.
* Adds a new `SNTEndpointSecurityTreeAwareClient` which clients subclass from to automatically have the tree updated before they run.
* Adds a `ProcessToken` to the core `Message` type passed through Santa, which causes the tree to automatically "hold on" to process information, even after the process' exit event is received. This means the clients can get process information out of the tree at any point, even in (delayed) async processing.
* Adds the basic configuration knobs to change which annotations are enabled (and if none are, disables the tree entirely).

N.B. Due to the last bullet above, while this code does technically begin to interact with event processing, the tree remains entirely disabled unless the config key is set.

2024-03-06 21:04 UTC, mlw requested changes

2024-03-06 21:04 UTC, mlw commented on Source/santad/EventProviders/SNTEndpointSecurityTreeAwareClient.mm
> +- (bool)handleContextMessage:(Message &)esMsg {
Add some comments about how this enforces specific event types are subscribed and will prevent messages from flowing to subclasses if those events were not directly subscribed.

2024-03-13 17:16 UTC, kallsyms commented on Source/santad/EventProviders/EndpointSecurity/Enricher.h
> +  Enricher(std::shared_ptr<process_tree::ProcessTree> pt);
Makes sense to me - changed and test changes reverted.

2024-03-13 19:26 UTC, mlw requested changes

2024-03-13 19:26 UTC, mlw commented on Source/santad/EventProviders/SNTEndpointSecurityClient.mm
> +      return;
We probably want a call to record metrics here.

2024-03-13 19:26 UTC, mlw commented on Source/santad/EventProviders/SNTEndpointSecurityTreeAwareClient.mm
> +// ES guarantees logical consistency within a client (e.g. forks always preceed exits),
preceed --> precede

2024-03-14 02:16 UTC, mlw approved these changes

2024-03-14 15:31 UTC, merged