Proto serializer
google/santa pull request #897
Opened 2022-10-04 20:49 UTC by mlw

* Add enhanced protobuf schema
* Add protobuf serializer
* Reorganize common serializer code into a serializer utilities file
* Remove "rules_proto_grpc" from the workspace, replace with "com_google_protobuf"

2022-10-05 01:44 UTC, mlw commented on Source/santad/EventProviders/EndpointSecurity/EnrichedTypes.h
Note: Almost all changes in this file are adding move constructors, deleting copy constructors, and adding accessors for enriched members

2022-10-11 21:29 UTC, pmarkowsky requested changes

2022-10-12 23:52 UTC, mlw commented on Source/common/TestUtils.mm
> +    .is_platform_binary = true,
No. Currently only new tests I've added use function.

2022-10-12 23:53 UTC, mlw commented on WORKSPACE
> +protobuf_deps()
In the PR adopting fsspool I've left a comment.

2022-10-13 01:03 UTC, pmarkowsky commented on Source/common/TestUtils.mm
> +    .is_platform_binary = true,
Yeah I realized afterwards that this was only for testing that we do handle serializing the value.

2022-10-13 02:04 UTC, mlw commented on Source/common/santa.proto
> +package santa.pb;
Done

2022-10-13 02:04 UTC, mlw commented on Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
> +      pb_fd->set_type_name(type_name.data(), type_name.length());
Done

2022-10-13 02:04 UTC, mlw commented on Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
> +std::string_view GetFileDescriptorTypeName(uint32_t fdtype) {
Done

2022-10-13 02:04 UTC, mlw commented on Source/common/santa.proto
> +  string type_name = 3;
Done

2022-10-13 17:23 UTC, pmarkowsky approved these changes
LGTM.

2022-10-13 17:52 UTC, merged