Fix SNTFileInfoTest for macOS 13
google/santa pull request #977
Opened 2022-12-21 23:18 UTC by pmarkowsky

This PR updates `SNTFileInfo` unit tests to account for Safari coming from a [cryptex](https://eclecticlight.co/2022/11/16/cryptex-how-a-custom-iphone-is-changing-macos-updates/) on macOS 13. Also skips the KEXT test on macOS 13 due to KEXTs moving into the kernel cache.

Fixes #886

2022-12-21 23:19 UTC, russellhancox requested changes

2022-12-21 23:19 UTC, russellhancox commented on Source/common/SNTFileInfoTest.m
> +    XCTAssertEqualObjects(sut.path, @"/System/Safari.app/Contents/MacOS/Safari");
s/System/Applications

2022-12-21 23:21 UTC, russellhancox approved these changes

2022-12-22 03:59 UTC, mlw approved these changes

2022-12-22 15:37 UTC, merged